# Generated by Django 4.0 on 2025-08-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtimechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': 'Chat Group', 'verbose_name_plural': 'Chat Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Group Message', 'verbose_name_plural': 'Group Messages'},
        ),
    ]
